### ISSUE TITLE
Suggestion to Oxygen Plugin

### ISSUE THREAD

**Issue by Smiil3** [GoldenPotato137/OxygenSystem#4]
Hello, I want to thank you for this plugin, I would like to suggest if it is possible to add a give command to each special block, because /oxygen get is like a kind of whole kit and I would like to make a shop where players can buy oxygen tank separately as well as for generators, thank you very much and the plugin works without problems on 1.19.2 (purpur).

**Comment by GoldenPotato137** [comment]
No problem, I'll finish it asap and package it into a new release along with other recent updates. 
Thank you for your suggestion.

**Comment by GoldenPotato137** [comment]
I am glad to inform you that we have finished new update v1.2. 
In v1.2, you can get specified items via ```/oxygen get [item1] [item2] ...```
