### ISSUE TITLE
Give Command | OxygenSystem

### ISSUE THREAD

**Issue by Smiil3** [GoldenPotato137/OxygenSystem#9]
Hello, I tried to use the command /oxygen get [item] [playername], but I saw that it does not work, there is no give command?, would it be possible to add it? Thanks for your time and your support !

**Comment by GoldenPotato137** [comment]
Thanks to @DoubleNico, now you can use give command to give anyplayer anything in this plugin. HH
Here is the Dev release:  [https://github.com/GoldenPotato137/OxygenSystem/releases/tag/1.3](https://github.com/GoldenPotato137/OxygenSystem/releases/tag/1.3)
